### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/lovely.recipe#1]
Is this project still "in use"?
Or is this a project to be archived?

@icemac ? or anybody else? @mgedmin - you did the last commit

Just asking before somebody puts some effort into fixing the build.

https://travis-ci.org/zopefoundation/lovely.recipe

**Comment by mgedmin** [comment]
I've never used lovely.recipe (and in fact have no idea what it does). All of my commits here were random "let's try to fix things" janitorial drive-through commits.

(The last commit was due to me running `check-python-versions ~/src/zopefoundation/*`, then doing a `git wm --all` which is my git alias that runs `git status` everywhere I have checkouts, noticing a weird `doc.txt` and realizing that running `python setup.py --classifiers` produces this file as a side effect.  Prior to that I had a shell one-liner go though all zopefoundation repos and mass-replace old versions of bootstrap.py with a then-current version of bootstrap.py.)

**Comment by icemac** [comment]
Fixed in 37a32ac.
